### PR TITLE
Allow allocated project name to be displayed in Coldfront UI on detailed Project view

### LINKED ISSUE #118: Display `Allocated Project Name` in Project Detail
It is possible to display an attribute for the allocations in the project detailed view under the "Information" column of the table. This setting is controlled by the config and env variable `ALLOCATION_ATTRIBUTE_VIEW_LIST`

https://github.com/ubccr/coldfront/blob/eaf90d26f4c6f76addc5ac62de202b6be9196d6a/coldfront/config/core.py#L49

Screenshot 2024-05-16 at 9 53 50 AM

This would significantly improve the UX for managing projects when there are multiple allocations for the same resource, therefore we should use this opportunity to display the project name.

### PR DESCRIPTION
**Pull request by QuanMPhm**
Closes #118 , I've edited the local_settings.py to allow the `Allocated Project Name` setting be displayed

### CODE REVIEW

**Review by knikolla — APPROVED** [review]

**Comment by knikolla** [comment]
@QuanMPhm have you done some testing and can share some pictures showing how it looks? Also can you see what happens if an allocation doesn't have that attribute yet?

**Comment by QuanMPhm** [comment]
@knikolla This is what I see when running the `coldfront-nerc` docker-compose file. The allocation for "Chemistry-cgray" has the attribute "Allocated Project Name" and "Allocated Project ID" set, but only the former is shown.
Screenshot 2024-05-29 at 4 48 41 PM

**Comment by QuanMPhm** [comment]
Is it a good idea to share screenshots like this on Github?

**Comment by knikolla** [comment]
> Is it a good idea to share screenshots like this on Github?

As long as it doesn't have any private information, yes. Thanks.

**Comment by knikolla** [comment]
@Milstein @jtriley the above change is a user-facing change that will show an allocation's `Allocated Project Name` in the allocations list of a project as per screenshot above.

**Review by jtriley — APPROVED** [review]

**Pull request merged**
